//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WildCrest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EntryMember_Billing
    {
        public int Bill_ID { get; set; }
        public string Price_Without_Gst { get; set; }
        public string Gst_Amount { get; set; }
        public string Price_With_Gst { get; set; }
        public string Members { get; set; }
        public string Total_Amount { get; set; }
        public string Amount_Paid { get; set; }
        public string Mode_Of_Payment { get; set; }
        public string Date_Of_Billing { get; set; }
        public Nullable<int> Billed_By { get; set; }
        public Nullable<int> Member_ID { get; set; }
    }
}
