//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WildCrest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_InventoryUsage
    {
        public int ID { get; set; }
        public Nullable<int> InventoryID { get; set; }
        public Nullable<double> Used_Qty { get; set; }
        public string Description { get; set; }
        public string Used_Date { get; set; }
        public Nullable<int> MenusBillingDetailsID { get; set; }
        public Nullable<int> BillNo { get; set; }
        public string GST_NonGST_Bill { get; set; }
        public Nullable<bool> IsBuffetFood { get; set; }
    }
}
