//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WildCrest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BarBillingMode
    {
        public int ID { get; set; }
        public Nullable<int> Bar_Bill_Number { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Mode_Of_Pay { get; set; }
    }
}
