//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WildCrest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BarBillingSection
    {
        public int Bill_Number { get; set; }
        public string Customer_Name { get; set; }
        public string Phone { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> UserID { get; set; }
        public string PaymentDate { get; set; }
        public Nullable<double> GST { get; set; }
        public Nullable<double> PriceWithoutTax { get; set; }
        public Nullable<int> TableID { get; set; }
        public string Table_Status { get; set; }
        public Nullable<System.TimeSpan> Order_Time { get; set; }
        public string OrderTakenBy { get; set; }
        public string Mode_Of_Payment { get; set; }
        public Nullable<int> Billed_By { get; set; }
        public Nullable<double> Discount { get; set; }
    }
}
